### ISSUE TITLE
ChatGPT Error in Version 7.4 (Server and Desktop)

### ISSUE THREAD

**Issue by T-Herrmann-WI** [ONLYOFFICE/onlyoffice.github.io#217] opened 2023-06-27 18:46 UTC
I have a OpenAI Pro Account and a valid token and get this error message:
"You have exceeded your current allotment.Please check your plan and billing details."

We use OnlyOffice EE Version 7.4 Document Server and tested desktop too. 
ChatGPT Plugin version 1.1.0

Any Idea?

Thank you. 

Best Tim Herrmann

**Comment by VladimirProkofiev52** [comment] 2023-06-29 09:52
Hello!, @T-Herrmann-WI 
You may have used all tokens.
Try to enter another key for openai or upgrade the balance on the openai.com tariff.

**Comment by T-Herrmann-WI** [comment] 2023-06-29 11:21
Dear [VladimirProkofiev52](https://github.com/VladimirProkofiev52), yes I used two different tokens with normal and pro OpenAI account with same error. The previous GPT plugin version did worked with this OpenAI Token. Best Tim

**Comment by VladimirProkofiev52** [comment] 2023-06-29 13:27
Please log in to your OpenAi account and make sure you have an available quota.
(example in screenshot)
![image](https://github.com/ONLYOFFICE/onlyoffice.github.io/assets/86404945/eb9d420d-74e4-40cd-bdb6-b783e4f8f7c5)

**Comment by T-Herrmann-WI** [comment] 2023-06-29 13:51
Thank you. This was the Problem. I just thought it's enough to pay for ChatGPT Plus but it's different you have to pay extra for the API Tokens. Sorry, my mistake.

**Comment by DenisDeeSign** [comment] 2023-06-30 08:17
I'm close this issue since the problem is not on our side. Feel free to create a new one if you got further questions or suggestions for improving plugin.

**Closed by DenisDeeSign** 2023-06-30 08:17 UTC
